language: node_js

node_js:
- '6'

addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
        
install:
- npm install

script: true

before_deploy:
- cat .netrc >> $HOME/.netrc
- chmod 0600 /home/travis/.netrc
- heroku apps
- heroku apps | grep -q dariamorgun-$TRAVIS_BRANCH || heroku apps:create dariamorgun-$TRAVIS_BRANCH
- heroku git:remote -a dariamorgun-$TRAVIS_BRANCH

deploy:
  provider: heroku
  api_key: 58cb1078-3146-4342-9b5b-4e927a2e4321
  app: dariamorgun-$TRAVIS_BRANCH
  on: $TRAVIS_BRANCH

after_deploy:
- ./node_modules/.bin/wdio wdio.conf || travis_terminate 1
